pipeline {
    agent any 
        stages {
          stage ("Build") {
              steps {
                  sh 'docker build -t image1 .'
              }
          }
          stage ('configure') {
              steps {
                  sh 'docker run -itd --name auth -p 5000:5000 image1'
              }
          }
    }
}
